# Add your additional Hyprland configurations here
gesture = 3, horizontal, workspace


# Pindah ke jendela berikutnya dalam grup (mirip Alt+Tab tapi khusus grup)
bind = ALT, TAB, changegroupactive, f

# Opsional: Jika ingin pindah ke jendela sebelumnya

bind = ALT SHIFT, TAB, changegroupactive, b
group {
    groupbar {
        enabled = false # Mematikan bar di atas grup sepenuhnya
        
        # ATAU jika ingin tetap ada tapi tidak makan tempat (super tipis):
         height = 0
         font_size = 0
         render_titles = false
    }
}

